# Generated by Django 4.1.2 on 2023-04-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_customerconfig_ep1_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerconfig",
            name="amuont",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="customerconfig",
            name="channel_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="customerconfig",
            name="ex_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="customerconfig",
            name="provider_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
