# Generated by Django 4.1.2 on 2023-04-16 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_alter_customerconfig_provider_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerconfig",
            old_name="provider_id",
            new_name="provider",
        ),
    ]
