# Generated by Django 4.1.2 on 2023-04-19 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_rename_provider_id_customerconfig_provider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
    ]
