# Generated by Django 4.1.2 on 2023-04-19 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_remove_customer_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerconfig",
            name="status",
        ),
    ]
