# Generated by Django 4.1.2 on 2023-05-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_customerconfig_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
