# Generated by Django 4.1.2 on 2023-05-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_customer_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerconfig",
            name="active",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
