# Generated by Django 4.1.2 on 2023-05-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_customerconfig_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerconfig",
            name="number_tp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
