# Generated by Django 4.1.2 on 2023-05-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0015_alter_customerconfig_number_tp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerconfig",
            name="amuont",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
