# Generated by Django 4.1.2 on 2023-03-28 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("prc", models.FloatField(default=0)),
                ("pre_prc", models.FloatField(default=0)),
                ("side", models.IntegerField(default=0)),
                ("updated", models.DateTimeField(null=True)),
                ("created", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "market_price",
            },
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("typ", models.IntegerField(default=0)),
                ("side", models.IntegerField(default=0)),
                (
                    "number_ep",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("ep1", models.FloatField(blank=True, default=0, null=True)),
                ("ep2", models.FloatField(blank=True, default=0, null=True)),
                ("ep3", models.FloatField(blank=True, default=0, null=True)),
                ("ep4", models.FloatField(blank=True, default=0, null=True)),
                (
                    "number_tp",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "sl_number",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("Llv", models.FloatField(blank=True, default=0, null=True)),
                (
                    "lv_typ",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "en_user",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "job_name",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                (
                    "exchange",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.exchange",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.provider",
                    ),
                ),
            ],
            options={
                "db_table": "signal",
            },
        ),
        migrations.CreateModel(
            name="SignalOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=200)),
                ("api_key", models.CharField(max_length=100)),
                ("api_secret", models.CharField(max_length=100)),
                ("api_passphrase", models.CharField(max_length=100)),
                ("sig_typ", models.CharField(max_length=100)),
                ("side", models.IntegerField(default=0)),
                ("symb", models.CharField(max_length=20)),
                ("amount_db", models.FloatField(default=0)),
                ("pr_sym_db", models.FloatField(default=0)),
                ("pr_sym_set", models.FloatField(default=0)),
                ("ep", models.FloatField(default=0)),
                ("ep_opt", models.FloatField(default=0)),
                ("sl", models.FloatField(default=0)),
                ("trail_en", models.IntegerField(default=0)),
                ("trail_tp", models.IntegerField(default=0)),
                ("trail_sl", models.IntegerField(default=0)),
                ("status", models.IntegerField(default=0)),
                ("number", models.IntegerField(default=1)),
                ("job", models.CharField(max_length=200)),
                ("bin_order_id", models.CharField(max_length=20)),
                ("amount_set", models.IntegerField(default=0)),
                ("ep_pre", models.IntegerField(default=0)),
                ("updated", models.DateTimeField(null=True)),
                ("created", models.DateTimeField(null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.customer",
                    ),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.exchange",
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="signals.signal",
                    ),
                ),
            ],
            options={
                "db_table": "signal_order",
            },
        ),
        migrations.CreateModel(
            name="SisgnalOrderDt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=100)),
                ("symb", models.CharField(max_length=20)),
                ("tp", models.FloatField(default=0)),
                ("tp_am", models.FloatField(default=0)),
                ("status", models.IntegerField(default=1)),
                ("bin_order_id", models.CharField(max_length=20)),
                ("updated", models.DateTimeField(null=True)),
                ("created", models.DateTimeField(null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="signals.signalorder",
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="signals.signal",
                    ),
                ),
            ],
            options={
                "db_table": "signal_order_dt",
            },
        ),
        migrations.CreateModel(
            name="SigOrderSl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=100)),
                ("user_id", models.IntegerField(default=0)),
                ("symb", models.CharField(max_length=20)),
                ("sl", models.FloatField(default=0)),
                ("status", models.IntegerField(default=0)),
                ("number", models.IntegerField(default=1)),
                ("bin_order_id", models.CharField(max_length=20)),
                ("amount_set", models.FloatField(default=0)),
                ("updated", models.DateTimeField(null=True)),
                ("created", models.DateTimeField(null=True)),
                (
                    "signal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="signals.signalorder",
                    ),
                ),
            ],
            options={
                "db_table": "signal_order_sl",
            },
        ),
        migrations.CreateModel(
            name="SignalDt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tp", models.FloatField(default=0)),
                ("tp_percent", models.PositiveIntegerField(default=0)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                (
                    "signal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="signals.signal",
                    ),
                ),
            ],
            options={
                "db_table": "signal_dt",
            },
        ),
    ]
