# Generated by Django 4.1.2 on 2023-04-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalorder',
            name='amount_set',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='signalorder',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signalorder',
            name='ep_pre',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='signalorder',
            name='side',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='signalorder',
            name='sig_typ',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signalorder',
            name='sl',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='signalorder',
            name='symb',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signalorder',
            name='trail_en',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='signalorder',
            name='trail_sl',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='signalorder',
            name='trail_tp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='signalorder',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
