# Generated by Django 4.1.2 on 2023-04-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signals", "0002_alter_signalorder_amount_set_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketprice",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
