# Generated by Django 4.1.2 on 2023-05-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signals", "0003_alter_marketprice_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="signal",
            name="active",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
