# Generated by Django 4.1.2 on 2023-05-02 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signals", "0004_signal_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signal",
            name="active",
        ),
    ]
